language: dart
sudo: required
dist: trusty
dart:
  - stable
  - beta
  - dev
before_script:
  - pub run tekartik_travis_ci_flutter:install
  - source $(pub run tekartik_travis_ci_flutter:env)
  - pub run chrome_travis:init
  - source $(pub run chrome_travis:env_rc)
script:
  - dart tool/travis.dart
