language: dart
sudo: required
dist: trusty
dart:
  - stable
  - beta
  - dev
addons:
  chrome: stable
before_script:
  - pub run tekartik_travis_ci_flutter:install
  - source $(pub run tekartik_travis_ci_flutter:env)
script:
  - cd repo_support
  - dart pub get
  - dart run tool/travis.dart
