name: tekartik_prefs_repo
description: idb_sqflite repo
version: 0.1.0
homepage: https://github.com/tekartik/prefs.dart
author: alex <alex@tekartik.com>
publish_to: none

environment:
  sdk: '>=2.10.0-0 <3.0.0'

dev_dependencies:
  pedantic: '>=1.4.0 <3.0.0'
  tekartik_travis_ci_flutter:
    git:
      url: git://github.com/tekartik/travis_ci_flutter.dart
      ref: dart2
    version: '>=0.1.0'
  chrome_travis:
    git:
      url: git://github.com/tekartik/chrome_travis.dart
      ref: dart2
    version: '>=0.1.0'
  process_run: '>=0.10.1'
  # include all from git so that it makes a dependency check
  tekartik_prefs_sembast:
    git:
      url: git://github.com/tekartik/prefs.dart
      path: prefs_sembast
      ref: dart2
  tekartik_prefs:
    git:
      url: git://github.com/tekartik/prefs.dart
      path: prefs
      ref: dart2
  tekartik_prefs_browser:
    git:
      url: git://github.com/tekartik/prefs.dart
      path: prefs_browser
      ref: dart2
  tekartik_prefs_test:
    git:
      url: git://github.com/tekartik/prefs.dart
      path: prefs_test
      ref: dart2

