name: tekartik_prefs_sembast
description: Prefs on sembast.
version: 0.1.0
homepage:
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  tekartik_prefs:
    git:
      url: https://github.com/tekartik/prefs.dart
      path: prefs
      ref: dart3a
    version: '>=0.1.0'
  sembast: ">=3.7.4+3"
  path: ">=1.9.0"


  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a
dev_dependencies:
  build_runner: ">=2.4.13"
  build_test: '>0.10.0'
  test: ">=1.24.0"
  tekartik_prefs_test:
    git:
      url: https://github.com/tekartik/prefs.dart
      path: prefs_test
      ref: dart3a
  process_run: ">=1.2.1+1"
resolution: workspace

