name: tekartik_prefs_sembast
description: Prefs on sembast.
version: 0.1.0
homepage:
publish_to: none

environment:
  sdk: '>=2.12.0-259.16.beta <3.0.0'

dependencies:
  tekartik_prefs:
    git:
      url: git://github.com/tekartik/prefs.dart
      path: prefs
      ref: null_safety
    version: '>=0.1.0'
  sembast: '>=3.0.0'
  path:


dev_dependencies:
  build_runner: '>0.10.0'
  build_test: '>0.10.0'
  dev_test: '>=0.13.0+1'
  test:
  tekartik_prefs_test:
    git:
      url: git://github.com/tekartik/prefs.dart
      path: prefs_test
      ref: null_safety
  process_run: '>=0.10.2'

dependency_overrides:
  tekartik_prefs:
    path: ../prefs
  tekartik_prefs_test:
    path: ../prefs_test