name: tekartik_prefs_sembast
description: Prefs on sembast.
version: 0.1.0
author:
homepage:

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  tekartik_prefs:
    git:
      url: git://github.com/tekartik/prefs.dart
      path: db
    version: '>=0.1.0'
  sembast: '>=2.0.0'
  path:


dev_dependencies:
  build_runner: '>0.10.0'
  build_test: '>0.10.0'
  dev_test: '>=0.13.0+1'
  test:
  tekartik_prefs_test:
    git:
      url: git://github.com/tekartik/prefs.dart
      path: db_test
  process_run: '>=0.10.2'

dependency_overrides:
  tekartik_prefs:
    path: ../prefs
  tekartik_prefs_test:
    path: ../prefs_test

