name: tekartik_prefs_browser
description: Prefs on top of local storage for Browser support
version: 0.1.0
#homepage: https://www.example.com
#author: alexr <email@example.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  tekartik_prefs:
    git:
      url: git://github.com/tekartik/prefs.dart
      path: prefs
      ref: dart2
    version: '>=0.1.0'

dev_dependencies:
  build_runner: '>0.10.0'
  build_test: '>0.10.0'
  build_web_compilers: '>=0.4.0'
  test:
  dev_test: '>=0.13.0+1'
  tekartik_prefs_test:
    git:
      url: git://github.com/tekartik/prefs.dart
      path: prefs_test
      ref: dart2
  process_run:

dependency_overrides:
  tekartik_prefs:
    path: ../prefs
  tekartik_prefs_test:
    path: ../prefs_test
