name: tekartik_prefs_browser
description: Prefs on top of local storage for Browser support
version: 0.2.0
publish_to: none
#homepage: https://www.example.com
#author: alexr <email@example.com>

environment:
  sdk: ^3.5.0

dependencies:
  tekartik_prefs:
    git:
      url: https://github.com/tekartik/prefs.dart
      path: prefs
      ref: dart3a
    version: '>=0.1.0'
  web: '>0.5.0'
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a
dev_dependencies:
  build_runner: ">=2.4.13"
  build_test: '>0.10.0'
  build_web_compilers: ">=4.0.11"
  test: ">=1.24.0"
  tekartik_prefs_test:
    git:
      url: https://github.com/tekartik/prefs.dart
      path: prefs_test
      ref: dart3a
  process_run: ">=1.2.0+3"

dependency_overrides:
  #web: ">=1.0.0 <1.1.0"
  tekartik_prefs:
    path: ../prefs
  tekartik_prefs_test:
    path: ../prefs_test
