name: tekartik_prefs_browser
description: Prefs on top of local storage for Browser support
version: 0.2.0
publish_to: none
#homepage: https://www.example.com
#author: alexr <email@example.com>

environment:
  sdk: ^3.9.0

dependencies:
  tekartik_prefs:
    git:
      url: https://github.com/tekartik/prefs.dart
      path: prefs
    version: '>=0.1.0'
  web: '>0.5.0'
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
dev_dependencies:
  build_runner: ">=2.4.13"
  build_test: '>0.10.0'
  build_web_compilers: ">=4.0.11"
  test: ">=1.24.0"
  tekartik_prefs_test:
    git:
      url: https://github.com/tekartik/prefs.dart
      path: prefs_test
  process_run: ">=1.2.1+1"
resolution: workspace

