name: tekartik_prefs_test
description: Prefs testing helpers
version: 0.2.0
publish_to: none

environment:
  sdk: '>=3.4.0-0 <4.0.0'

dependencies:
  tekartik_prefs:
    git:
      url: https://github.com/tekartik/prefs.dart
      path: prefs
      ref: dart3a
    version: '>=0.1.0'
  test:
dev_dependencies:
  build_runner: '>0.10.0'
  build_test: '>0.10.0'
  process_run:

dependency_overrides:
  tekartik_prefs:
    path: ../prefs
