name: tekartik_prefs_test
description: Prefs testing helpers
version: 0.2.0
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  cv: ">=1.1.0+4"
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a
  tekartik_prefs:
    git:
      url: https://github.com/tekartik/prefs.dart
      path: prefs
      ref: dart3a
    version: '>=0.1.0'
  test: ">=1.24.0"
dev_dependencies:
  build_runner: ">=2.4.13"
  build_test: '>0.10.0'
  process_run: ">=1.2.1+1"

dependency_overrides:
  tekartik_prefs:
    path: ../prefs
