name: tekartik_prefs_test
description: Prefs testing helpers
version: 0.2.0
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  tekartik_prefs:
    git:
      url: https://github.com/tekartik/prefs.dart
      path: prefs
      ref: dart2_3
    version: '>=0.1.0'
  dev_test: '>=0.13.0+1'

dev_dependencies:
  test: any
  build_runner: '>0.10.0'
  build_test: '>0.10.0'
  process_run:

dependency_overrides:
  tekartik_prefs:
    path: ../prefs